language: python
python:
  - "2.7"
env:
  - DJANGO=1.7
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install -r requirements.pip --use-mirrors
  - pip install -q -e . --use-mirrors
before_script:
   - mkdir -p shippable/testresults
   - mkdir -p shippable/codecoverage
script:
  - python manage.py test
